### ISSUE TITLE
observe_on(AsyncIOScheduler()) doesn't work for emissions from other threads

### ISSUE THREAD

**Issue by adamples** [ReactiveX/RxPY#169] opened 2017-03-15 22:27 UTC
Actually it can work quite randomly for more complicated programs. Basically when events are emitted using any scheduler that spawns threads (so `NewThreadScheduler`, `ThreadPoolScheduler`, `TimeoutScheduler`) the observer callbacks are not executed until some other event happens.

Example code (DebugTAP is a class that just prints received data):

    loop = asyncio.get_event_loop()

    # events will be emitted using TimeoutScheduler
    rx.Observable.interval(100) \
        .take(5) \
        .observe_on(AsyncIOScheduler(loop)) \
        .subscribe(DebugTAP())

    # nothing happens for 2 seconds
    loop.run_until_complete(asyncio.sleep(2))

    # here the numbers are printed, all at once, because loop was woken up
    loop.run_until_complete(asyncio.sleep(2))

I traced this problem down to the interaction between `ScheduledObserver` and `AsyncIOScheduler`. The issue is that `ScheduledObserver` schedules its `run` method on the target scheduler _but in the context of the source scheduler_, so possibly in a thread other than the one where the loop is running. `AsyncIOScheduler` in turn calls loop's `call_soon` and `call_later` methods, which are not thread-safe [1]. The result is that the loop is not aware of the new task that was just scheduled and waits for other events (like I/O or end of sleep as in my example).

The issue would be much less apparent in a program where the loop is constantly waken up, but then still unneccessary latency is introduced.

The simple solution would be to replace `call_soon` and `call_later` with `call_soon_threadsafe` and `call_later_threadsafe` respectively [2].

[1] https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop
[2] https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading

**Comment by NavidHt** [comment] 2017-12-02 15:05
If we enable asyncio debug mode it throws `RuntimeError` exception with a message complaining about **thread-safety**:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  ...
  File ".../rx/concurrency/mainloopscheduler/asyncioscheduler.py", line 28, in schedule
    handle = self.loop.call_soon(interval)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 576, in call_soon
    self._check_thread()
  ...
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
```
Exception's stack trace suggests that the problem is at `AsyncIOScheduler`, where calling [`self.loop.call_soon(interval)`](https://github.com/ReactiveX/RxPY/blob/065e974e1b1811fd0b1958ff2cab1dc2c535b470/rx/concurrency/mainloopscheduler/asyncioscheduler.py#L28). I applied the solution suggested in previous message, replacing `call_soon` and `call_later` with `call_soon_threadsafe` and `call_later_threadsafe` respectively. The error is gone and It seems everything is working.

The following code will regenerate the error:
```Python
import asyncio
from rx import Observable
from rx.concurrency.mainloopscheduler.asyncioscheduler import AsyncIOScheduler

Observable.interval(100) \
    .observe_on(AsyncIOScheduler()) \
    .subscribe(on_next=lambda x: print(x))

asyncio.get_event_loop().set_debug(True)
asyncio.get_event_loop().run_forever()
```

**Comment by MainRo** [comment] 2018-06-29 13:30
@dbrattli , can this fix be merged in master and/or release/v1.6.x ? I am also interested in getting this fix upstream. Do you want a PR ?

**Closed** 2018-12-25 11:09 UTC
