### ISSUE TITLE
Quick question: schedule_periodic(0.0, ...)

### ISSUE THREAD

**Issue by erikkemperman** [ReactiveX/RxPY#370] opened 2019-05-08 13:31 UTC
Quick question, there seem to be two competing approaches to implementing `schedule_periodic(0.0, ...)`:
- Invoke the action once, and then don't re-schedule
- Invoke the action very often, as quickly as possible

The first is mostly true for the schedulers which inherit the `SchedulerBase` implementation, the second is due to overriding that.

If I want to make things consistent for all schedulers, which approach should be used?

I kind of think the first one is a bit weird, then we are simply doing `schedule()` but with a different callback signature. The second one is probably what people would expect, but might be a bit dangerous (e.g. CurrentThreadScheduler would never return from this call unless one of the action invocations disposes "itself").

**Comment by jcafhe** [comment] 2019-05-10 15:51
I would say the second is the expected behavior. 

It appears that the current behavior (which I believe is dued to the lines below) was introduced in PR #306, from commit e1fe18a86ef06aab3230486893412ece10d4a307.

https://github.com/ReactiveX/RxPY/blob/93f94ca88da3a7209637b16bb87519b8cc4c396a/rx/concurrency/schedulerbase.py#L129-L130

**Comment by erikkemperman** [comment] 2019-05-10 16:31
Yes, I think the eventletscheduler did not handle the zero case properly and I had noticed other schedulers doing the first option (one shot).

But I agree, I think it should be the second, if we manage to fix issues that might occur in the various implementations.

**Comment by dbrattli** [comment] 2019-05-11 14:07
Schedule periodic should schedule as fast as possible (i.e second behaviour). The `schedule_periodic` should be removed from `SchedulerBase` since not all schedulers can or should implement it (e.g CurrentThreadScheduler). In .NET they have a separete interface `ISchedulerPeriodic` used by schedulers that support periodic scheduling.

Thus we should have a separate type e.g SchedulerPeriodicBase with a base impl. of schedule_periodic, and then the schedulers that can impl. periodic scheduling can inherit from this baseclass to signal that they support periodic scheduling, and override if they need to.

PS: Nice read about periodic scheduling (not mentioning the zero case): https://blogs.msdn.microsoft.com/rxteam/2012/06/20/reactive-extensions-v2-0-release-candidate-available-now/

**Comment by erikkemperman** [comment] 2019-05-11 14:38
All right, thanks, good that there seems to be agreement.

I’d like to finish up my current effort — I think I found a robust way to more or less uniformly test all schedulers, which includes asserting that things run in the right threads, at the expected times, and propagating the right arguments to the callback. The pattern I am using is safe for schedulers which might eat exceptions and so on. I will add the zero periodic case also.

While doing this I am finding some minor issues in individual implementations that become apparent with the more thorough tests, and will address those as they arise.

Afterwards, I can try to refactor the whole package to split the period case in a separate base class (and typing), and at the same time I hope I can get rid of considerable redundancy around the various schedule methods calling on one another.

Finally I would like to propose some naming changes, which if you agree to them ought to be done before 3.0-beta:

SchedulerBase -> Scheduler (like it was done for Observer and Observable)?

concurrency (package) -> scheduler (not all schedulers offer concurrency)?

mainloopscheduler (package) -> split into eventloop and mainloop?

What do you think?

**Comment by dbrattli** [comment] 2019-05-11 14:41
Yes, good suggestions!

**Comment by jcafhe** [comment] 2019-05-11 15:23
@dbrattli I've started to read your link and the part about time and periodic scheduling is very instructive, also quite complex (and depressing too :cold_sweat: ). Since the blog post seems to be old (2012), I was wondering if some of these ideas have been implemented (local scheduler, dispatch scheduler, long and short term queues, ...)?

> Thus we should have a separate type e.g SchedulerPeriodicBase with a base impl. of schedule_periodic, and then the schedulers that can impl. periodic scheduling can inherit from this baseclass to signal that they support periodic scheduling, and override if they need to.

I agree :+1: 

@erikkemperman, agree with your suggestions too.

**Comment by dbrattli** [comment] 2019-05-11 15:27
@jcafhe Yes they have. Look at https://github.com/dotnet/reactive/tree/master/Rx.NET/Source/src/System.Reactive/Concurrency

However RxPY was forked from RxJS (based on an earlier version of Rx.NET) so we lost much of the scheduler stuff since RxJS does not have threads.

**Comment by erikkemperman** [comment] 2019-05-11 15:50
I will look at that article as well, sounds interesting (I've been thinking about separate queues for long/short term items, actually, no need to sort long-away items all the time until they're almost up).

Another quick question, which I should throw out there before the next release, is about the license -- there are two license files in the main directory. I guess the Apache license is the right one? Is the microsoft one (still) applicable?

Technically I think the Apache license requires a pre-amble in every single source file... I don't know if you feel strongly about the distinctions, but if not, perhaps MIT license would be more convenient?

**Comment by dbrattli** [comment] 2019-05-11 20:59
About the license. The reason for Apache is that RxPY was initially a rewrite of RxJS ([Apache License](https://github.com/Reactive-Extensions/RxJS/blob/master/license.txt)) for Python and it was actually released though Microsoft Open Technologies in 2013 and I had to sign a Contribution License Agreement (CLA) with them. At the time they used Apache for all OSS. Microsoft Open Technologies was [merged](https://www.zdnet.com/article/microsoft-shutters-its-standalone-open-tech-open-source-subsidiary/) back into Microsoft. A few year later, Microsoft started recommending MIT for all OSS produced internally since that makes it easier/safer for Microsoft to reuse the code themselves, so I think it should be perfectly OK to switch to MIT if we want. I use MIT for my other projects so I'll accept a PR for a license change to MIT.

**Closed** 2019-05-30 11:04 UTC
