### ISSUE TITLE
Possible bug when disconnecting subscriber from iterable

### ISSUE THREAD

**Issue by mikus** [ReactiveX/RxPY#62] opened 2015-11-03 18:45 UTC
I try to use iterator as observable but I want this observable to be as cold as possible, i.e. generate new values only when there is any subscriber. But when I dispose subscriber iterator still works. The code is as follow:

``` python
from time import sleep
from rx import Observable
from rx.concurrency import new_thread_scheduler


def myiterator():
    for i in range(100):
       sleep(1)
       print('Publishing value: {0}'.format(i))
       yield i

source = Observable.from_(myiterator(), scheduler=new_thread_scheduler)
subscription = source.subscribe(
    lambda v: print("Value published: {0}".format(v)),
    lambda e: print("Error! {0}".format(e)),
    lambda: print("Completed!")
)

sleep(3)
print('Before dispose')
subscription.dispose()
print('After dispose')
sleep(3)
print('Finish')
```

and the output is:

```
Publishing value: 0
Value published: 0
Publishing value: 1
Value published: 1
Before dispose
After dispose
Publishing value: 2
Publishing value: 3
Publishing value: 4
Finish
```

I suppose there should be no publishing value after subscriber disposal. Am I correct?

**Comment by jdreaver** [comment] 2015-11-04 16:01
@dbrattli, would this be fixed by creating a `disposed = [False]` list, a function to dispose with, and then creating a `CompositeObservable` with the cancelable from `schedule_recursive` (just like in [`catch`](https://github.com/ReactiveX/RxPY/blob/master/rx/linq/observable/catch.py#L112), for example)?

**Comment by dbrattli** [comment] 2015-11-05 21:39
The problem is really that `Observable.from_()` uses `schedule_recursive()` which probably don't make sense when using the `NewThreadScheduler`. The dispose would actually work if recursive scheduling wasn't used, so it's probably better to make an overload for `schedule_recursive()` for the `NewThreadScheduler` that doesn't recurse. I need to look a bit more into this.

**Comment by mikus** [comment] 2015-11-06 15:32
I don't know is it the problem in scheduler or default implementation of `schedule_recursive()`. 
BTW with `timeout_scheduler` situation is exactly the same.

**Comment by dbrattli** [comment] 2015-11-07 17:08
There's a problem with the `NewThreadScheduler` that the iterator is called on different threads. It should be called by the same "new" thread. I have a fix for that by letting the `NewThreadScheduler` use the `EventLoopScheduler` to shedule actions, but still some problems with the dispose logic. I will see if I can figure it out this weekend.

**Comment by mikus** [comment] 2015-11-10 14:37
I think the new implementation using `EventLoopScheduler` still generates new thread for each iteration.

**Comment by dbrattli** [comment] 2015-11-10 21:10
@mikus could you give an example? Your example above now produces the following output with the latest master/develop branch and with added thread info:

```
Thread-1:Publishing value: 0
Thread-1:Value published: 0
Thread-1:Publishing value: 1
Thread-1:Value published: 1
MainThread:Before dispose
MainThread:After dispose
Thread-1:Publishing value: 2
MainThread:Finish
```

There is a single publish after dispose, which I think is OK given that dispose is best effort, and publish happens on a different thread than dispose.

**Comment by mikus** [comment] 2015-11-10 21:53
I'm really sorry for misleading but I'd changed scheduler to `timeout_scheduler` and forgot rollback after master branch update. Thus `new_thread_scheduler` works correctly now but the same problem still exists with `timeout_scheduler`.

**Comment by dbrattli** [comment] 2015-11-10 22:04
No problem, and thanks for testing. I'll try to find out what the problem is with `timeout_scheduler`.

**Comment by dbrattli** [comment] 2015-11-10 22:17
Actually it's the same problem as with `NewThreadScheduler` and the fix is to use `EventLoopScheduler` the same way as `NewThreadScheduler`. Thus it doesn't make any sense to have a `TimerScheduler` anymore, since `EventLoopScheduler` uses `Timer` for timeouts. We should probably swap it for a `ThreadPoolScheduler` which would be much more interesting to have.

**Closed** 2019-01-26 11:17 UTC
